Blog_Project_Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('account_app.urls')),
    path('', include('blog_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.urls import path
from . import views


app_name = "account_app"
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register_user, name='register'),
    path('edit', views.edit_user_profile, name='edit_pofile'),
]

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'
urlpatterns = [
    path('detail/<slug:slug>', views.PostDetailView.as_view(), name='detail'),
    path('list', views.PostListView.as_view(), name='list'),
    path('category/<int:pk>', views.category_details, name='category_detail'),
    path('search', views.search, name='search_list'),
    path('contactus', views.contactus, name='contact_us'),
    path('like', views.like, name='like')
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from blog_app.manager import Article_Publish_Blog
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Article(models.Model):
    auther = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده')
    title = models.CharField(max_length=80, verbose_name='عنوان')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی')
    body = models.TextField(verbose_name='متن')
    image = models.ImageField(upload_to='image/article', verbose_name='عکس')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')
    is_published = models.BooleanField(default=True, verbose_name='عمومی شود')
    status = models.BooleanField(default=True, verbose_name='موقعیت')
    slug = models.SlugField(blank=True, default=' ')
    objects = models.Manager()
    filter_manager = Article_Publish_Blog()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_app:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.title} - {self.body[:30]}'

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comment', verbose_name='مقاله')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment', verbose_name='کاربر')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='relies')
    body = models.TextField(verbose_name='متن')
    created_add = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return self.body[:50]

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'


class Message(models.Model):
    name = models.CharField(max_length=50, verbose_name='نام')
    email = models.EmailField(verbose_name='ایمیل')
    title = models.CharField(max_length=70, verbose_name='عنوان')
    text = models.TextField(verbose_name='متن')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام ها'


class Like(models.Model):
    user = models.ForeignKey(User, related_name='like', on_delete=models.CASCADE, verbose_name='کاربر')
    article = models.ForeignKey(Article, related_name='like', on_delete=models.CASCADE, verbose_name='مقاله')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return f'{self.article.title} - {self.user.username}'

    class Meta:
        verbose_name = 'لایک'
        verbose_name_plural = 'لایک ها'

blog_app/forms.py
from django import forms
from django.core.validators import ValidationError

from blog_app.models import Message


class ContactUs(forms.Form):
    YOUR_TYPE_CHOICES = ['Blogger', 'Viewer']

    choices_field = forms.ChoiceField(widget=forms.RadioSelect, choices=YOUR_TYPE_CHOICES)
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    subject = forms.CharField(max_length=150)
    message = forms.CharField(max_length=300)

    def clean(self):
        subject = self.cleaned_data.get('subject')
        message = self.cleaned_data.get('message')

        if subject == message:
            raise ValidationError('subject and message are same')

    def clean_name(self):
        name = self.cleaned_data.get('name')

        if '@' in name:
            raise ValidationError('You can not use @ in your name')


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'title', 'text')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your title',
                'style': 'max-width: 500px'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Email',
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your title',
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your text',
            })

        }

blog_app/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from .models import Article, Category, Comment, Message, Like
from .forms import ContactUs, MessageForm
from django.views.generic.list import ListView
# from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import LoadLogin
from django.views.generic.detail import DetailView
from django_ajax.decorators import ajax
from django.contrib.auth.decorators import login_required


# Create your views here.

def post_detail(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == 'POST':
        parent_id = request.POST.get('parent_id')
        body = request.POST.get('body')
        Comment.objects.create(body=body, article=article, parent_id=parent_id, user=request.user)
    return render(request, 'blog_app/post-details.html', {'article': article})


def post_list(request):
    articles = Article.filter_manager.published()
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 1)
    page_list = paginator.get_page(page_number)
    return render(request, 'blog_app/post-list.html', {'articles': page_list})


def category_details(request, pk=None):
    category = Category.objects.get(id=pk)
    articles = category.article_set.filter(is_published=True)
    return render(request, 'blog_app/post-list.html', {'articles': articles})


def search(request):
    if request.method == 'GET':
        q = request.GET.get('q')
        articles = Article.objects.filter(title__icontains=q)
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 1)
        page_list = paginator.get_page(page_number)
        return render(request, 'blog_app/post-list.html', {'articles': page_list})


def contactus(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            title = form.cleaned_data.get('title')
            text = form.cleaned_data.get('text')
            Message.objects.create(name=name, email=email, title=title, text=text)

        # instance = form.save(commit=False)
        # instance.name = 'ali'
        # instance.save()

    else:
        form = MessageForm()
    return render(request, 'blog_app/contact-us.html', {'form': form})


class PostListView(LoadLogin, ListView):
    model = Article
    context_object_name = 'articles'
    paginate_by = 1
    template_name = 'blog_app/post-list.html'
    queryset = Article.objects.filter(is_published=True)


class PostDetailView(DetailView):
    model = Article
    template_name = 'blog_app/post-details.html'


@login_required
def like(request, slug, pk):
    if request.method == 'POST':
        if request.user.like(article_id=pk, article__slug=slug).exists():
            likes = Like.objects.get(user_id=request.user.id, article__slug=slug)
            likes.delete()
        else:
            Like.objects.create(article_id=pk, user_id=request.user.id)

blog_app/templates/blog_app/base.html
$(document).ready(function(){
  $(document).on('click', '#like', function(event){
    event.preventDefault();
    var pk = $(this).attr('value');
    $.ajax({
      type: 'POST',
      url: '{% url "likes" %}',
      data: {
            'post_id': pk,
            'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response){
              $('#like-section').html(response['form'])
            },
            error: function(rs, e){
              console.log(rs.responseText);
            },
          });
     });
})

blog_app/templates/blog_app/contact-us.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>contact us</h4>
                            <h2>let’s stay in touch!</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->


    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12">

                                                    {{ form }}

                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">Send
                                                            Message
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="sidebar-item contact-information">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>


{% endblock %}

blog_app/templates/blog_app/like_section.html
{{ total_likes }} Like {{ total_likes|pluralize }}

{% if request.user.is_authenticated %}
<form action="{% url 'blog_app:like' %" method="POST">
    {% csrf_token %}
    {% if is_liked %}
        <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
    {% else %}
        <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
    {% endif %}
</form>
{% endif %}

blog_app/templates/blog_app/post-details.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Post Details</h4>
                            <h2>{{ article.title }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>Creative HTML Template For Bloggers!</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="{{ article.image.url }}" alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>Lifestyle</span>
                                        <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">{{ article.auther }}</a></li>
                                            <li><a href="#">{{ article.created }}</a></li>
                                            <li><a href="#">10 Comments</a></li>
                                        </ul>
                                        <p>{{ article.body }}</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
{#                                                        <li><i class="fa fa-tags"></i></li>#}
                                                        <div id="like-section">
                                                            <li><a href="#" class="fa fa-heart"></a><div>2</div></li>
{#                                                            {% include 'blog_app/like_section.html' %}#}
                                                        </div>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#"> Twitter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item comments">
                                    <div class="sidebar-heading">
                                        <h2>4 comments</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for comment in article.comment.all %}
                                                {% if comment.parent == None %}
                                                    <li>
                                                        <div class="author-thumb">
                                                            {% if comment.user.profile.image %}
                                                                <img src="{{ comment.user.profile.image.url }}"
                                                                     alt="">
                                                            {% else %}
                                                                <img src="{% static 'images/icons/user.png' %}"
                                                                     alt="">
                                                            {% endif %}
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ comment.user.get_full_name }}<span>{{ comment.created_add }}</span>
                                                            </h4>
                                                            <p>{{ comment.body }}</p>
                                                            <button onclick="set_value({{ comment.id }})"
                                                                    class="btn btn-primary">Reply
                                                            </button>
                                                        </div>
                                                    </li>
                                                    {% for reply in comment.relies.all %}
                                                        <li class="replied">
                                                            <div class="author-thumb">
                                                                {% if reply.user.profile.image %}
                                                                    <img src="{{ reply.user.profile.image.url }}"
                                                                         alt="">
                                                                {% else %}
                                                                    <img src="{% static 'images/icons/user.png' %}"
                                                                         alt="">
                                                                {% endif %}
                                                            </div>
                                                            <div class="right-content">
                                                                <h4>{{ reply.user.get_full_name }}<span>{{ reply.created_add }}</span>
                                                                </h4>
                                                                <p>{{ reply.body }}</p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% endif %}
                                            {% endfor %}


                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="col-lg-12">
                                    <div class="sidebar-item submit-comment">
                                        <div class="sidebar-heading">
                                            <h2>Your comment</h2>
                                        </div>
                                        <div class="content">
                                            <form id="comment" action="#" method="post">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <input type="hidden" name="parent_id" id="parent_id" value="">
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                    <textarea name="body" rows="6" id="body"
                                                              placeholder="Type your comment" required=""></textarea>
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <button type="submit" id="form-submit" class="main-button">
                                                                Submit
                                                            </button>
                                                        </fieldset>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <button class="alert-danger"><a href="{% url 'account_app:login' %}">for send comment
                                    you should login </a></button>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include 'include/recent-posts.html' %}
            </div>
        </div>
    </section>
    <script>

        function set_value(id) {

            document.getElementById('parent_id').value = id;
            window.location.href = '#body'
        }

    </script>
{% endblock %}

blog_app/templates/blog_app/post-list.html
{% extends 'base.html' %}
{% load static %}



{% block main %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Blog Entries</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>Creative HTML Template For Bloggers!</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in articles %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ article.category.first }}</span>
                                            <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.auther }}</a></li>
                                                <li><a href="#">{{ article.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ article.body }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Best Templates</a>,</li>
                                                            <li><a href="#">TemplateMo</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-lg-12">
                                {% if page_obj.has_other_pages %}

                                    <ul class="page-numbers">
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}



                                        {% for i in page_obj.paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="active"><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}


                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-right"></i></a></li>
                                        {% endif %}
                                    </ul>

                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'include/recent-posts.html' %}
            </div>
        </div>
    </section>


{% endblock %}