Blog_Project_Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('account_app.urls')),
    path('', include('blog_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.urls import path
from . import views


app_name = "account_app"
urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register_user, name='register'),
    path('edit', views.edit_user_profile, name='edit_pofile'),
]

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'
urlpatterns = [
    path('detail/<slug:slug>', views.PostDetailView.as_view(), name='detail'),
    path('list', views.PostListView.as_view(), name='list'),
    path('category/<int:pk>', views.category_details, name='category_detail'),
    path('search', views.search, name='search_list'),
    path('contactus', views.contactus, name='contact_us'),
    path('like', views.like, name='like')
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path('', views.home, name='home')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
          rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <!--

    TemplateMo 551 Stand Blog

    https://templatemo.com/tm-551-stand-blog

    -->
</head>

<body>

<!-- ***** Preloader Start ***** -->
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<!-- ***** Preloader End ***** -->

<!-- Header -->
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if request.resolver_match.url_name == 'home' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'home_app:home' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="about.html">About Us</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link {% if request.resolver_match.url_name == 'list' %} active {% endif %}" href="{% url 'blog_app:list' %}">Blog Entries</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog_app:contact_us' %}">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            {% if user.profile.image %}
                                <span><img src="{{ user.profile.image.url }}" class="rounded-circle"
                                           style="width: 30px; height: 30px" alt="profile"></span>
                            {% else %}
                                <img src="{% static 'images/icons/user.png' %}" style="width: 25px; height: 25px">
                            {% endif %}
                            <div>
                                <a class="Dark link"
                                   href='/admin'>{{ request.user.first_name }} {{ request.user.last_name }}</a>


                                <a class="Secondary link" href="{% url 'account_app:logout' %}">logout</a>
                            </div>
                        {% else %}
                            <div>
                                <a class="Dark link" href="{% url 'account_app:login' %}">Login</a>
                                |
                                <a class="Dark link" href="{% url 'account_app:register' %}">Register</a>
                            </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>


{% block main %}

{% endblock %}


<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Behance</a></li>
                    <li><a href="#">Linkedin</a></li>
                    <li><a href="#">Dribbble</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>Copyright 2020 Stand Blog Co.

                        | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>

<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>
</body>
</html>